### ISSUE TITLE
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}

### ISSUE THREAD

**Issue by mariobodemann** [M2Mobi/MarkyMark-Android#18]
Hello,

I am trying to build the example Android app using your lovely library and the Contentful❤️ flavor, sadly I'm faced with this `attribute at index 6` exception:

```
2018-06-29 13:41:33.754 10694-10694/com.contentful.tea.kotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.contentful.tea.kotlin, PID: 10694
    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
        at android.widget.TextView.readTextAppearance(TextView.java:3548)
        at android.widget.TextView.<init>(TextView.java:924)
        at android.widget.TextView.<init>(TextView.java:869)
        at com.m2mobi.markymarkandroid.HeaderDisplayItem.create(HeaderDisplayItem.java:38)
        at com.m2mobi.markymarkandroid.HeaderDisplayItem.create(HeaderDisplayItem.java:19)
        at com.m2mobi.markymark.Converter.convert(Converter.java:49)
        at com.m2mobi.markymark.MarkyMark.parseMarkdown(MarkyMark.java:62)
        at com.m2mobi.markymarkandroid.MarkyMarkView.setMarkdown(MarkyMarkView.java:59)
        at com.contentful.tea.kotlin.MainActivity$onCreate$1$1.run(MainActivity.kt:61)
```

I'm using this code to try and add markdown views:

```
val markyMark = MarkyMarkAndroid.getMarkyMark(
    applicationContext,
    ContentfulFlavor()
) { _, url -> Log.d(LOG_TAG, url) }

courses.forEach{
    it.lessons.forEach {
        it.modules.forEach {
            if (it is LessonModule.Copy) {
                markyMark.parseMarkdown(it.copy).forEach {
                    base_linear_layout.addView(it) // base_linear is a LinearLayout for testing
                }
            }
        }
    }
}
```

and my `gradle.build` looks like this:

```
implementation 'com.github.m2mobi.MarkyMark-Android:markymark-android:0.2.3'
implementation 'com.github.m2mobi.MarkyMark-Android:markymark-contentful:0.2.3'
```

Is there anything obvious I am doing wrong?

Greetings,
Mario

**Comment by mariobodemann** [comment]
Hey,

following up, is there a way to get me a timeline when you are looking at this?

I'd love to use your Android lib, but right now this issue is holding me back from using it...

Greetings,
Mario

**Comment by KilianSteenman** [comment]
Hi @mariobodemann, Your setup code looks alright. Do you have an example of the content you're trying to parse? I am trying to reproduce your issue but without success.

**Comment by mariobodemann** [comment]
Hey,

hmmmmm that is odd then. I tried using MarkyMark in this branch early in the development: https://github.com/contentful/the-example-app.kotlin/blob/add/markymark/app/src/main/kotlin/com/contentful/tea/kotlin/MainActivity.kt .

I can sent you my sample MD next week, but there should be nothing more but images, links, bullet lists, italics and bold marks used.

Thanks for looking into it,
Mario

**Comment by KilianSteenman** [comment]
Thanks! Was able to reproduce it using your repository/branch. Will let you know when I know more.

**Comment by KilianSteenman** [comment]
Creating a MarkyMark instance requires an Activity context for theming. Was able to get the code running by using the MainActivity as context:

`val markyMark = MarkyMarkAndroid.getMarkyMark(
                        this@MainActivity,
                        ContentfulFlavor()
                    ) { _, url -> Log.d(LOG_TAG, url) }`

Will check if we can change this to use the Application context.

**Comment by mariobodemann** [comment]
Hey,

that is some great news, I'll have to see how and if I can update the example app to use MarkyMark.

Thanks so far.

**Comment by KilianSteenman** [comment]
Next release will force the use of an Activity as a temporary solution. We are looking into a different solution.
