### ISSUE TITLE
How to style bullet and list ticks?

### ISSUE THREAD

**Issue by illyabusigin** [M2Mobi/MarkyMark-Android#22]
Hi there,

I'm working on the Android equivalent of my application and am trying to style the bullet color and list ticks a a specific color. I've read the styling instructions and updated my styles.xml with something like so:

```xml
<style name="list" parent="MarkyMarkList">
        <item name="android:textColor">#00ff00</item>
    </style>
```
This applies the color to the entire list item. Is there any way to apply the color to the number like you can do on iOS? For iOS I do:

```swift
markdownView.styling.listStyling.bulletColor = .red
```

Any help or tips to point me in the right direction would be greatly appreciated :)

**Comment by NielsMasdorp** [comment]
Sorry for the late reply, but it is possible to provide custom drawables for bullet points. Not as easily as on iOS though. `MarkyMarkAndroid.getMarkyMark()` uses a default `ListDisplayItem` mapping:

```
viewConverter.addMapping(ListDisplayItem(
    context,
    R.dimen.list_margin,
    intArrayOf(R.drawable.bullet_filled, R.drawable.bullet, R.drawable.dash, R.drawable.square))
)
```

When you construct the `MarkyMark` instance yourself using the builder you can change these values to be any drawable you like.
