### ISSUE TITLE
Enable clickable URL span in BlockQuote

### ISSUE THREAD

**Issue by ilians** [M2Mobi/MarkyMark-Android#40]
Like the ParagraphDisplayItem, a QuoteDisplayItem could also contain an inline link. Currently the QuoteDisplayItem however does not set the link movement method which does nog enable the clickable behaviour for the URLSpans. 

https://github.com/M2mobi/MarkyMark-Android/blob/f9b521e0d33463aeb124d321ae37541474368e6b/android/src/main/java/com/m2mobi/markymarkandroid/ParagraphDisplayItem.kt#L22-L27

https://github.com/M2mobi/MarkyMark-Android/blob/f9b521e0d33463aeb124d321ae37541474368e6b/android/src/main/java/com/m2mobi/markymarkandroid/QuoteDisplayItem.kt#L23-L29

This could be solved setting the following movement method of the QuoteDisplayItem.
`textView.movementMethod = LinkMovementMethod.getInstance()`

**Comment by patrickhoette** [comment]
No longer relevant in new rewrite of the library. Will be supported there
